import { verifyPayload } from "@sarayan/core-evidence";
import { CheckCircle2, XCircle } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { eq } from "drizzle-orm";
import { MarketingShell } from "@/components/marketing/chrome";
import { Alert, Badge, Card, CardContent } from "@/components/ui";
import { db } from "@/db";
import { evidencePacks } from "@/db/schema";
import { DEFAULT_LOCALE, formatDateTime, isLocale, translator, type Locale } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Evidence pack verification",
  robots: { index: false, follow: false },
};

/**
 * Public verification.
 *
 * Deliberately unauthenticated: the recipient of an evidence pack is a bank or
 * an auditor who has no Sarayan account and should not need one. The page
 * reveals only what the pack itself already discloses — entity, scope, counts,
 * timestamp — and never the underlying records.
 */
export default async function VerifyHashPage({
  params,
}: {
  params: Promise<{ locale: string; hash: string }>;
}) {
  const { locale: raw, hash: rawHash } = await params;
  const locale: Locale = isLocale(raw) ? raw : DEFAULT_LOCALE;
  const t = translator(locale);
  const hash = rawHash.toLowerCase().replace(/[^0-9a-f]/g, "");

  const pack =
    hash.length === 64
      ? (
          await db
            .select()
            .from(evidencePacks)
            .where(eq(evidencePacks.hash, hash))
            .limit(1)
        )[0]
      : undefined;

  const authentic = pack ? verifyPayload(pack.canonicalPayload, pack.hash) : false;
  const summary = (pack?.summary ?? {}) as Record<string, number>;

  return (
    <MarketingShell locale={locale} path="/verify">
      <div className="mx-auto max-w-2xl px-4 py-20">
        <h1 className="text-3xl font-semibold tracking-tight text-ink-950 dark:text-ink-50">
          {t("evidence.verifyTitle")}
        </h1>

        {!pack ? (
          <Alert tone="danger" className="mt-8">
            <span className="flex items-center gap-2">
              <XCircle className="size-4 shrink-0" aria-hidden />
              {t("evidence.notFound")}
            </span>
          </Alert>
        ) : !authentic ? (
          <Alert tone="danger" className="mt-8">
            {locale === "ar"
              ? "فشل التحقق: البيانات المخزّنة لا تُنتج هذه البصمة. تواصل معنا فوراً."
              : "Verification failed: the stored data does not reproduce this hash. Contact us immediately."}
          </Alert>
        ) : (
          <>
            <Alert tone={pack.revokedAt ? "warning" : "success"} className="mt-8">
              <span className="flex items-center gap-2">
                <CheckCircle2 className="size-4 shrink-0" aria-hidden />
                {pack.revokedAt ? t("evidence.revoked") : t("evidence.verified")}
              </span>
            </Alert>

            <Card className="mt-6">
              <CardContent className="p-6">
                <dl className="grid gap-4 sm:grid-cols-2">
                  <Row label={locale === "ar" ? "النطاق" : "Scope"} value={pack.scope} />
                  <Row
                    label={locale === "ar" ? "أُنشئت في" : "Generated"}
                    value={formatDateTime(pack.generatedAt, locale)}
                  />
                  <Row
                    label={locale === "ar" ? "أنشأها" : "Generated by"}
                    value={pack.generatedByName}
                  />
                  <Row
                    label={locale === "ar" ? "عدد السجلات" : "Records"}
                    value={String(pack.recordCount)}
                  />
                </dl>

                <div className="mt-6 flex flex-wrap gap-2 border-t border-ink-100 pt-5 dark:border-ink-800">
                  <Badge tone="valid">
                    {summary.valid ?? 0} {locale === "ar" ? "سارية" : "valid"}
                  </Badge>
                  <Badge tone="due_soon">
                    {summary.dueSoon ?? 0} {locale === "ar" ? "تقترب" : "due soon"}
                  </Badge>
                  <Badge tone="critical">
                    {summary.critical ?? 0} {locale === "ar" ? "حرجة" : "critical"}
                  </Badge>
                  <Badge tone="expired">
                    {summary.expired ?? 0} {locale === "ar" ? "منتهية" : "expired"}
                  </Badge>
                </div>

                <p className="mt-6 break-all font-mono text-[11px] text-ink-400" dir="ltr">
                  {pack.hash}
                </p>
              </CardContent>
            </Card>

            <p className="mt-6 text-sm leading-relaxed text-ink-500 dark:text-ink-400">
              {locale === "ar"
                ? "هذا التحقق يؤكد أن محتوى الحزمة لم يُعدّل منذ إنشائها. لا يؤكد اكتمال سجل المؤسسة — ذلك مسؤوليتها وحدها."
                : "This confirms the pack's contents have not been altered since generation. It does not assert that the organisation's register is complete — only they can attest to that."}
            </p>
          </>
        )}

        <Link
          href={`/${locale}/verify`}
          className="mt-8 inline-block text-sm text-brand-700 hover:underline dark:text-brand-400"
        >
          {locale === "ar" ? "تحقّق من حزمة أخرى" : "Verify another pack"}
        </Link>
      </div>
    </MarketingShell>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs uppercase tracking-wide text-ink-500 dark:text-ink-400">{label}</dt>
      <dd className="mt-1 text-sm font-medium text-ink-900 dark:text-ink-100">{value}</dd>
    </div>
  );
}
