import { withCommonFields, type DocumentTypeDefinition } from "./types";

/** Saudi Arabia document types. */
export const SAUDI_DOCUMENT_TYPES: DocumentTypeDefinition[] = [
  {
    code: "SA_COMMERCIAL_REGISTRATION",
    country: "SA",
    jurisdiction: "national",
    category: "corporate",
    holderKind: "entity",
    nameEn: "Commercial registration (CR)",
    nameAr: "السجل التجاري",
    aliases: ["sijil tijari", "CR certificate", "commercial register"],
    issuingAuthority: "Ministry of Commerce",
    issuingAuthorityAr: "وزارة التجارة",
    typicalValidityMonths: 12,
    renewalLeadDays: 45,
    typicalRenewalCost: { amount: 1200, currency: "SAR" },
    penalties: [
      { fromDay: 1, toDay: null, amount: 100, currency: "SAR", perDay: false, note: "Per month late, plus suspension of government services" },
    ],
    blocks: ["SA_CHAMBER_MEMBERSHIP", "SA_IQAMA", "SA_MUNICIPALITY_LICENCE", "SA_VAT_CERTIFICATE"],
    requires: [],
    consequences: [
      { effect: "Government e-services are suspended across Absher and Qiwa", severity: "blocking" },
      { effect: "Bank accounts can be frozen", severity: "blocking" },
      { effect: "Monthly fines accrue", severity: "financial" },
    ],
    fields: withCommonFields(
      { key: "crNumber", label: "CR number", kind: "text", required: true, hint: "10-digit commercial registration number", pattern: "^\\d{10}$" },
      { key: "unifiedNumber", label: "Unified number (700)", kind: "text" },
      { key: "activities", label: "Activities", kind: "text" },
      { key: "capital", label: "Capital", kind: "number" },
    ),
    seo: {
      slug: "saudi-commercial-registration-renewal",
      title: "Saudi commercial registration (CR) renewal: cost, timeline, penalties",
      metaDescription:
        "How to renew a Saudi commercial registration, what it costs, the fines for late renewal, and the government services that stop when it lapses.",
      intro: [
        "The Saudi commercial registration is the root of a company's entire government footprint. Almost every other document — Chamber membership, municipality licence, iqama issuance, VAT filing — hangs off it, and every one of them stops when the CR does.",
        "The renewal is inexpensive and largely automated through the Ministry of Commerce portal. The reason it still causes damage is that it fails quietly: services degrade before anyone connects the degradation to a lapsed registration.",
      ],
      steps: [
        {
          heading: "Confirm Chamber of Commerce membership is current",
          body: "The CR renewal is normally processed alongside a valid Chamber membership. An expired membership will stall the renewal at the payment stage.",
        },
        {
          heading: "Settle any Zakat or VAT obligations",
          body: "Outstanding filings with ZATCA can block the renewal. Check standing before you begin, not when the portal refuses.",
        },
        {
          heading: "Renew via the Ministry of Commerce portal",
          body: "Renewal is online and generally same-day once obligations are clear. The certificate is issued electronically.",
        },
        {
          heading: "Push the new date downstream",
          body: "Municipality licence, Chamber membership and iqama sponsorship all reference the CR. Update those records in the same session.",
        },
      ],
      faqs: [
        {
          question: "What happens if a Saudi CR expires?",
          answer:
            "Monthly fines accrue and government e-services tied to the entity are progressively suspended — including the ability to issue or renew iqamas for staff. Banking access can be affected.",
        },
        {
          question: "How long does CR renewal take?",
          answer:
            "Minutes online when Chamber membership and ZATCA obligations are clear. Days to weeks when they are not — which is why the lead time is 45 days, not 5.",
        },
      ],
      related: ["saudi-iqama-renewal", "saudi-chamber-of-commerce-renewal", "saudi-municipality-licence-renewal"],
    },
  },
  {
    code: "SA_IQAMA",
    country: "SA",
    jurisdiction: "national",
    category: "immigration",
    holderKind: "person",
    nameEn: "Iqama (residence permit)",
    nameAr: "الإقامة",
    aliases: ["residence permit", "muqeem", "residency card"],
    issuingAuthority: "General Directorate of Passports (Jawazat)",
    issuingAuthorityAr: "المديرية العامة للجوازات",
    typicalValidityMonths: 12,
    renewalLeadDays: 45,
    typicalRenewalCost: { amount: 9700, currency: "SAR" },
    penalties: [
      { fromDay: 1, toDay: 30, amount: 500, currency: "SAR", note: "First offence" },
      { fromDay: 31, toDay: null, amount: 1000, currency: "SAR", note: "Second offence, escalating to deportation" },
    ],
    blocks: ["SA_DRIVING_LICENCE"],
    requires: ["SA_COMMERCIAL_REGISTRATION", "SA_PASSPORT", "SA_GOSI_CERTIFICATE"],
    consequences: [
      { effect: "The employee cannot legally work or travel", severity: "blocking" },
      { effect: "Fines per worker, escalating to deportation on repeat", severity: "financial" },
      { effect: "Exit-re-entry visas cannot be issued", severity: "operational" },
    ],
    fields: withCommonFields(
      { key: "iqamaNumber", label: "Iqama number", kind: "text", required: true, hint: "10-digit, usually starts with 2", pattern: "^\\d{10}$" },
      { key: "passportNumber", label: "Passport number", kind: "text" },
      { key: "nationality", label: "Nationality", kind: "text" },
      { key: "profession", label: "Profession", kind: "text" },
      { key: "sponsorNumber", label: "Sponsor ID", kind: "text" },
    ),
    seo: {
      slug: "saudi-iqama-renewal",
      title: "Saudi iqama renewal requirements: cost, documents and fines",
      metaDescription:
        "Iqama renewal in Saudi Arabia: the levy, medical insurance requirement, GOSI standing, timeline, and the fines for renewing late.",
      intro: [
        "Iqama renewal is the single largest recurring compliance cost most Saudi employers carry, and the levy is charged whether or not the renewal happens on time. Late renewal adds a fine on top of a cost you were already paying.",
        "The dependency that catches companies out is not the levy — it is medical insurance and GOSI standing. Both must be current before the Jawazat will process the renewal, and both sit with different people in most organisations.",
      ],
      steps: [
        {
          heading: "Confirm medical insurance is active",
          body: "The employee's policy must be valid for the renewal period. An insurance renewal in flight is not the same as one in force.",
        },
        {
          heading: "Check GOSI registration and contributions",
          body: "Outstanding GOSI contributions block iqama renewal. Reconcile monthly rather than discovering it at renewal.",
        },
        {
          heading: "Pay the levy and file through Absher / Muqeem",
          body: "Once obligations are clear, the renewal is processed electronically and is usually immediate.",
        },
        {
          heading: "Verify the printed expiry",
          body: "Iqama expiry is recorded in Hijri on the card. Convert once, record the Gregorian date, and never re-derive it by hand.",
        },
      ],
      faqs: [
        {
          question: "What is the fine for late iqama renewal in Saudi Arabia?",
          answer:
            "Broadly SAR 500 for a first offence and SAR 1,000 for a second, with deportation possible on a third. The employer normally bears it.",
        },
        {
          question: "Can an iqama be renewed while GOSI is unpaid?",
          answer: "No. GOSI standing is checked as part of the renewal and unpaid contributions will block it.",
        },
        {
          question: "Is the iqama expiry Hijri or Gregorian?",
          answer:
            "The card shows Hijri. Convert it once on entry, store the Gregorian date, and alert on that — hand-converting each time is where errors enter.",
        },
      ],
      related: ["saudi-commercial-registration-renewal", "saudi-gosi-certificate", "saudi-work-permit-renewal"],
    },
  },
  {
    code: "SA_WORK_PERMIT",
    country: "SA",
    jurisdiction: "national",
    category: "labour",
    holderKind: "person",
    nameEn: "Work permit (Qiwa)",
    nameAr: "رخصة العمل",
    aliases: ["labour permit", "qiwa permit", "rukhsat amal"],
    issuingAuthority: "Ministry of Human Resources and Social Development",
    issuingAuthorityAr: "وزارة الموارد البشرية والتنمية الاجتماعية",
    typicalValidityMonths: 12,
    renewalLeadDays: 45,
    typicalRenewalCost: { amount: 9600, currency: "SAR" },
    penalties: [{ fromDay: 1, toDay: null, amount: 10000, currency: "SAR", note: "Employing without a valid permit" }],
    blocks: [],
    requires: ["SA_COMMERCIAL_REGISTRATION", "SA_IQAMA"],
    consequences: [
      { effect: "The establishment's Nitaqat band can be downgraded", severity: "blocking" },
      { effect: "Substantial per-worker fines", severity: "financial" },
    ],
    fields: withCommonFields(
      { key: "permitNumber", label: "Permit number", kind: "text" },
      { key: "profession", label: "Profession", kind: "text" },
      { key: "establishmentNumber", label: "Establishment number", kind: "text" },
    ),
    seo: {
      slug: "saudi-work-permit-renewal",
      title: "Saudi work permit renewal: Qiwa process, cost and Nitaqat impact",
      metaDescription:
        "Renewing a Saudi work permit through Qiwa: the levy, the link to iqama renewal, and how lapsed permits affect your Nitaqat band.",
      intro: [
        "The Saudi work permit and the iqama are renewed together in practice but are separate records with separate failure modes. The permit is what MHRSD sees; the iqama is what Jawazat sees.",
        "The consequence that matters most is indirect: lapsed permits feed into the establishment's Nitaqat classification, and a downgraded band restricts everything from new visas to service transfers.",
      ],
      steps: [
        {
          heading: "Confirm Saudization standing in Qiwa",
          body: "Check the establishment's current band before the renewal batch — a borderline band can flip on a handful of lapsed permits.",
        },
        {
          heading: "Pay the labour levy",
          body: "The levy is charged per expatriate worker and is due regardless of renewal timing.",
        },
        {
          heading: "Renew alongside the iqama",
          body: "Batching the two avoids the common failure where one is renewed and the other is not.",
        },
      ],
      faqs: [
        {
          question: "What is the fine for employing someone without a valid work permit in Saudi Arabia?",
          answer: "Fines start around SAR 10,000 per worker and escalate with repetition, alongside Nitaqat consequences.",
        },
      ],
      related: ["saudi-iqama-renewal", "saudi-gosi-certificate"],
    },
  },
  {
    code: "SA_CHAMBER_MEMBERSHIP",
    country: "SA",
    jurisdiction: "national",
    category: "corporate",
    holderKind: "entity",
    nameEn: "Chamber of Commerce membership",
    nameAr: "عضوية الغرفة التجارية",
    aliases: ["chamber subscription", "ghurfa"],
    issuingAuthority: "Federation of Saudi Chambers",
    issuingAuthorityAr: "اتحاد الغرف السعودية",
    typicalValidityMonths: 12,
    renewalLeadDays: 30,
    typicalRenewalCost: { amount: 800, currency: "SAR" },
    penalties: [],
    blocks: ["SA_COMMERCIAL_REGISTRATION"],
    requires: ["SA_COMMERCIAL_REGISTRATION"],
    consequences: [
      { effect: "Document attestation and CR renewal are blocked", severity: "blocking" },
    ],
    fields: withCommonFields({ key: "membershipNumber", label: "Membership number", kind: "text" }),
    seo: {
      slug: "saudi-chamber-of-commerce-renewal",
      title: "Saudi Chamber of Commerce membership renewal",
      metaDescription:
        "Chamber of Commerce membership renewal in Saudi Arabia: cost, timing, and why it gates your commercial registration renewal.",
      intro: [
        "Chamber membership is a small annual subscription that quietly gates two important things: attestation of company documents, and the commercial registration renewal itself.",
        "It is the cheapest item in the Saudi compliance stack and, per riyal, the most disruptive to miss.",
      ],
      steps: [
        {
          heading: "Renew through the Chamber portal",
          body: "Renewal is online and usually immediate. Categories and fees vary with company size.",
        },
        {
          heading: "Renew ahead of the CR, not with it",
          body: "Leave a clear thirty days so a payment or category dispute cannot delay the registration.",
        },
      ],
      faqs: [
        {
          question: "Is Chamber of Commerce membership mandatory in Saudi Arabia?",
          answer:
            "For companies holding a commercial registration, yes in practice — it is required for attestation services and for CR renewal.",
        },
      ],
      related: ["saudi-commercial-registration-renewal"],
    },
  },
  {
    code: "SA_GOSI_CERTIFICATE",
    country: "SA",
    jurisdiction: "national",
    category: "labour",
    holderKind: "entity",
    nameEn: "GOSI compliance certificate",
    nameAr: "شهادة التأمينات الاجتماعية",
    aliases: ["social insurance certificate", "tameenat"],
    issuingAuthority: "General Organization for Social Insurance",
    issuingAuthorityAr: "المؤسسة العامة للتأمينات الاجتماعية",
    typicalValidityMonths: 3,
    renewalLeadDays: 14,
    typicalRenewalCost: null,
    penalties: [{ fromDay: 1, toDay: null, amount: 2, currency: "SAR", perDay: false, note: "2% of unpaid contributions per month" }],
    blocks: ["SA_IQAMA", "SA_WORK_PERMIT"],
    requires: ["SA_COMMERCIAL_REGISTRATION"],
    consequences: [
      { effect: "Iqama and work permit renewals are blocked", severity: "blocking" },
      { effect: "Government tender pre-qualification fails", severity: "financial" },
    ],
    fields: withCommonFields({ key: "gosiNumber", label: "GOSI establishment number", kind: "text" }),
    seo: {
      slug: "saudi-gosi-certificate",
      title: "GOSI certificate in Saudi Arabia: validity, renewal and what it blocks",
      metaDescription:
        "The GOSI compliance certificate expires quarterly and gates iqama renewals and tender submissions. How to keep it current.",
      intro: [
        "The GOSI certificate has a short validity — often ninety days — which makes it the highest-frequency item in a Saudi compliance register and the one a quarterly review process reliably misses.",
        "It is also a gate: unpaid contributions block iqama renewals, so a lapse here shows up as an immigration problem before anyone looks at social insurance.",
      ],
      steps: [
        {
          heading: "Reconcile contributions monthly",
          body: "The certificate is a by-product of being up to date. Chasing the certificate without reconciling the contributions solves nothing.",
        },
        {
          heading: "Re-issue from the GOSI portal",
          body: "Once contributions are clear the certificate is generated instantly and can be downloaded as a PDF.",
        },
      ],
      faqs: [
        {
          question: "How long is a GOSI certificate valid?",
          answer: "Typically 90 days, which is why it needs an automated reminder rather than a calendar entry.",
        },
      ],
      related: ["saudi-iqama-renewal", "saudi-work-permit-renewal"],
    },
  },
  {
    code: "SA_MUNICIPALITY_LICENCE",
    country: "SA",
    jurisdiction: "national",
    category: "premises",
    holderKind: "asset",
    nameEn: "Municipality licence (Baladiya)",
    nameAr: "رخصة البلدية",
    aliases: ["baladiya licence", "municipal permit", "shop licence"],
    issuingAuthority: "Ministry of Municipal and Rural Affairs",
    issuingAuthorityAr: "وزارة الشؤون البلدية والقروية",
    typicalValidityMonths: 12,
    renewalLeadDays: 45,
    typicalRenewalCost: { amount: 3000, currency: "SAR" },
    penalties: [{ fromDay: 1, toDay: null, amount: 5000, currency: "SAR", note: "Operating without a valid licence, plus closure" }],
    blocks: [],
    requires: ["SA_COMMERCIAL_REGISTRATION", "SA_CIVIL_DEFENCE_SA"],
    consequences: [
      { effect: "The premises can be sealed by municipal inspectors", severity: "blocking" },
      { effect: "Substantial fines", severity: "financial" },
    ],
    fields: withCommonFields(
      { key: "licenceNumber", label: "Licence number", kind: "text" },
      { key: "premisesAddress", label: "Premises", kind: "text" },
      { key: "activity", label: "Permitted activity", kind: "text" },
    ),
    seo: {
      slug: "saudi-municipality-licence-renewal",
      title: "Saudi municipality (Baladiya) licence renewal: cost and closure risk",
      metaDescription:
        "Renewing a Baladiya licence in Saudi Arabia: prerequisites, civil defence approval, cost, and the risk of premises closure.",
      intro: [
        "The municipality licence is premises-level, not company-level, which is why multi-branch companies lose track of it: there is one CR but five licences, each on its own date.",
        "Enforcement is physical. An expired municipality licence is discovered by an inspector at the door, not by a portal notification.",
      ],
      steps: [
        {
          heading: "Renew civil defence approval first",
          body: "Fire safety approval is a precondition. It has its own inspection lead time — start there.",
        },
        {
          heading: "Confirm the CR covers the activity and the address",
          body: "Mismatches between the CR activity and the licensed activity are a common rejection reason.",
        },
        {
          heading: "Renew per branch",
          body: "Track one record per premises. A single company-level entry will hide four of your five renewal dates.",
        },
      ],
      faqs: [
        {
          question: "What happens if a Baladiya licence expires?",
          answer: "Fines and, on inspection, closure of the premises until the licence is regularised.",
        },
      ],
      related: ["saudi-commercial-registration-renewal"],
    },
  },
  {
    code: "SA_CIVIL_DEFENCE_SA",
    country: "SA",
    jurisdiction: "national",
    category: "premises",
    holderKind: "asset",
    nameEn: "Civil Defence licence",
    nameAr: "رخصة الدفاع المدني",
    aliases: ["fire safety licence", "difaa madani"],
    issuingAuthority: "General Directorate of Civil Defence",
    issuingAuthorityAr: "المديرية العامة للدفاع المدني",
    typicalValidityMonths: 12,
    renewalLeadDays: 60,
    typicalRenewalCost: { amount: 1000, currency: "SAR" },
    penalties: [{ fromDay: 1, toDay: null, amount: 5000, currency: "SAR", note: "Plus closure until compliant" }],
    blocks: ["SA_MUNICIPALITY_LICENCE"],
    requires: [],
    consequences: [
      { effect: "Municipality licence renewal is blocked", severity: "blocking" },
      { effect: "Premises closure following inspection", severity: "blocking" },
    ],
    fields: withCommonFields({ key: "licenceNumber", label: "Licence number", kind: "text" }),
    seo: null,
  },
  {
    code: "SA_VAT_CERTIFICATE",
    country: "SA",
    jurisdiction: "national",
    category: "tax",
    holderKind: "entity",
    nameEn: "VAT registration certificate",
    nameAr: "شهادة التسجيل في ضريبة القيمة المضافة",
    aliases: ["ZATCA certificate", "tax certificate"],
    issuingAuthority: "Zakat, Tax and Customs Authority",
    issuingAuthorityAr: "هيئة الزكاة والضريبة والجمارك",
    typicalValidityMonths: null,
    renewalLeadDays: 30,
    typicalRenewalCost: null,
    penalties: [],
    blocks: [],
    requires: ["SA_COMMERCIAL_REGISTRATION"],
    consequences: [{ effect: "Customer invoices may be rejected", severity: "operational" }],
    fields: withCommonFields({ key: "vatNumber", label: "VAT number", kind: "text", hint: "15-digit ZATCA number" }),
    seo: null,
  },
  {
    code: "SA_ZAKAT_CERTIFICATE",
    country: "SA",
    jurisdiction: "national",
    category: "tax",
    holderKind: "entity",
    nameEn: "Zakat certificate",
    nameAr: "شهادة الزكاة",
    aliases: ["zakat clearance", "ZATCA clearance certificate"],
    issuingAuthority: "Zakat, Tax and Customs Authority",
    issuingAuthorityAr: "هيئة الزكاة والضريبة والجمارك",
    typicalValidityMonths: 12,
    renewalLeadDays: 45,
    typicalRenewalCost: null,
    penalties: [],
    blocks: ["SA_COMMERCIAL_REGISTRATION"],
    requires: [],
    consequences: [
      { effect: "Government contracts and payment releases are blocked", severity: "financial" },
      { effect: "CR renewal can be blocked", severity: "blocking" },
    ],
    fields: withCommonFields({ key: "certificateNumber", label: "Certificate number", kind: "text" }),
    seo: null,
  },
  {
    code: "SA_PASSPORT",
    country: "SA",
    jurisdiction: "national",
    category: "immigration",
    holderKind: "person",
    nameEn: "Passport",
    nameAr: "جواز السفر",
    aliases: ["travel document"],
    issuingAuthority: "Issuing country's authority",
    issuingAuthorityAr: "سلطة بلد الإصدار",
    typicalValidityMonths: 120,
    renewalLeadDays: 180,
    typicalRenewalCost: null,
    penalties: [],
    blocks: ["SA_IQAMA"],
    requires: [],
    consequences: [
      { effect: "Iqama renewal is refused under six months of passport validity", severity: "blocking" },
    ],
    fields: withCommonFields(
      { key: "passportNumber", label: "Passport number", kind: "text", required: true },
      { key: "nationality", label: "Nationality", kind: "text" },
    ),
    seo: null,
  },
  {
    code: "SA_DRIVING_LICENCE",
    country: "SA",
    jurisdiction: "national",
    category: "vehicle",
    holderKind: "person",
    nameEn: "Driving licence",
    nameAr: "رخصة القيادة",
    aliases: ["rukhsat qiyada"],
    issuingAuthority: "General Department of Traffic",
    issuingAuthorityAr: "الإدارة العامة للمرور",
    typicalValidityMonths: 60,
    renewalLeadDays: 45,
    typicalRenewalCost: { amount: 400, currency: "SAR" },
    penalties: [{ fromDay: 1, toDay: null, amount: 300, currency: "SAR", note: "Driving on an expired licence" }],
    blocks: [],
    requires: ["SA_IQAMA"],
    consequences: [
      { effect: "The driver cannot legally operate company vehicles", severity: "blocking" },
      { effect: "Insurance claims may be refused", severity: "financial" },
    ],
    fields: withCommonFields({ key: "licenceNumber", label: "Licence number", kind: "text" }),
    seo: null,
  },
  {
    code: "SA_VEHICLE_REGISTRATION",
    country: "SA",
    jurisdiction: "national",
    category: "vehicle",
    holderKind: "vehicle",
    nameEn: "Vehicle registration (Istimara)",
    nameAr: "استمارة المركبة",
    aliases: ["istimara", "vehicle form", "registration card"],
    issuingAuthority: "General Department of Traffic",
    issuingAuthorityAr: "الإدارة العامة للمرور",
    typicalValidityMonths: 12,
    renewalLeadDays: 30,
    typicalRenewalCost: { amount: 300, currency: "SAR" },
    penalties: [{ fromDay: 1, toDay: null, amount: 500, currency: "SAR", note: "Driving with expired registration" }],
    blocks: [],
    requires: [],
    consequences: [
      { effect: "The vehicle can be impounded", severity: "blocking" },
      { effect: "Fines per stop", severity: "financial" },
    ],
    fields: withCommonFields(
      { key: "plateNumber", label: "Plate number", kind: "text", required: true },
      { key: "chassisNumber", label: "Chassis number", kind: "text" },
      { key: "make", label: "Make", kind: "text" },
    ),
    seo: null,
  },
];
